### PR TITLE
New Geom_ and Geom2d classes

### PR DESCRIPTION
**Pull request by nyholku**

### CODE REVIEW

**Comment by nyholku** [comment]
Hi Jerome,

thanks for reviewing. And sorry about #6 & #7, still learning the best way to use branches and made a silly mistake there.

Can you clarify the Standard_Type / getClass() issue.

I originally implemented the Standard_Type to get following (from the OCC bottle example) to compile and work:

		for (TopExp_Explorer aFaceExplorer = new TopExp_Explorer(myBody, TopAbs_ShapeEnum.FACE); aFaceExplorer.more(); aFaceExplorer.next()) {
			TopoDS_Face aFace = TopoDS.Face(aFaceExplorer.current());
			Geom_Surface aSurface = BRep_Tool.surface(aFace);
			if (aSurface instanceof Geom_Plane) {
			if (aSurface.DynamicType().equals(Geom_Plane.STANDARD_TYPE())) {
				Geom_Plane aPlane = aSurface.DownCast(aSurface);


I know realise the linage of `Geom_Plane` is wrong, it should `extend Geom_ElementarySurface`, with that I can write much better looking Java code:

			if (aSurface instanceof Geom_Plane) {
				Geom_Plane aPlane = (Geom_Plane) aSurface;

That compiles, BUT is does not work, `aSurface instanceof Geom_Plane` is never true for a reason I don't understand. And of course then `aSurface.getClass()==Geom_Plane.class` works neither.

Any idea what the problem might be?

**Comment by nyholku** [comment]
I see that the problem with  `instanceof ` (or  `getClass() `) here is that  `BRep_Tool.surface(aFace) ` instantiates  `Geom_Surface ` (of course) and not the dynamic object class. ATM I don't see what should be done ... `Dynamic_Type` works at some runtime cost, but can that cost be avoided, if  `BRep_Tool.surface() ` would be made to return the correct type, then that method would need to access the dynamic type. Guidance appreciated, while I'm +50 and have been programming +35 years (mostly C/C++ and Java with lots of asm and most of the usual suspects thrown in)  I'm a bit of noob where OCC and occjava are concerned.

**Comment by jeromerobert** [comment]
Ok I understand the problem thanks to your example. OccJava have and automatic downcast for `TopoDS_Shape` but not for `Geom_Geometry`. I'll think about it during the next week-end. It looks that we cannot implement it in the same way as https://github.com/jeromerobert/jCAE/blob/master/occjava/src/TopoDS.i#L103 because there is no enum for Geom_Geometry. But I should be able to find another way. The goal is that your example will looks like

```java
TopExp_Explorer aFaceExplorer = new TopExp_Explorer(myBody, TopAbs_ShapeEnum.FACE);
for (;aFaceExplorer.more(); aFaceExplorer.next()) {
    TopoDS_Face aFace = (TopoDS_Face) aFaceExplorer.current();
    Geom_Surface aSurface = BRep_Tool.surface(aFace);
    if (aSurface instanceof Geom_Plane) {
        Geom_Plane aPlane = (Geom_Plane)aSurface;
```

I'll keep you in touch

**Comment by jeromerobert** [comment]
@nyholku Could you try the jr/downcast branch ? My tests says it works. I'll merge it once you feel it's good.

**Comment by nyholku** [comment]
Hi,

thanks for that.

I checked out 'jr/downcast' and cherry picked your commits on top of my branch. There was some conflicts that I resolved (not 100% I did that correctly). Recompiled the SWIG stuff, which went fine. But on the Java side could not get `instance of Geom_Plane` to compile.

So I added to `Geom.i` 

    class Handle_Geom_Plane: public Handle_Geom_Surface
    {
    	Handle_Geom_Plane()=0;
    };

And then the code compiled and the bottle example executed correctly.

So I think you fix is correct.

I don't see why I had to add `class Handle_Geom_Plane: public Handle_Geom_Surface` when in your branch you have nothing like that.

But I guess it does not matter since you are going to merge you changes and I will then rebase my commits, if necessary, and issue a new pull request, right?

**Comment by nyholku** [comment]
ping ... if you have time to push your changes I can then rebase...

**Comment by jeromerobert** [comment]
Sorry for the long delay.

> So I added to Geom.i ...

I don't understand because this change is already in fa1a889

> ping ... if you have time to push your changes I can then rebase...

Done.

**Comment by nyholku** [comment]
Hi thanks for update and info. Must be my mistake, not too fluent with github workflow after five years or so ;) I will now try to proceed.

**Comment by nyholku** [comment]
I will close this pull request as I've created a new one based my new branch which I created based on your latest master branch.

**Pull request closed without merging**
